# This workflow is only intended to run when a pull-request is merged into the main branch
name: Main branch Workflow

on:
  push:
    branches: [main]

jobs:
  build_python_artifacts:
    name: Python Build
    uses: ./.github/workflows/python-build-and-lint.yml

  python_tests:
    name: Python Unit Tests
    needs: build_python_artifacts
    uses: ./.github/workflows/python-test-python-version.yml

  python_cross_platform:
    name: Python Cross Platform Build & Test
    uses: ./.github/workflows/python-cross-platform-support.yml

# Commenting out from main branch workflow till permissions aspect can be resolved for
# reconnecting automated page deployment. The below workflow is able to be ran manually
# allowing for the site to stay up to date.
  # build_and_deploy_documentation:
  #   name: Build and Deploy GitHub Pages
  #   uses: ./.github/workflows/sphinx.yml

  deploy_artifacts:
    name: Deploy Artifacts
    runs-on: ubuntu-22.04
    needs: build_python_artifacts
    permissions:
      # Important:  This permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Download Python Wheel
        uses: actions/download-artifact@v3
        with:
          name: aac_rest_api_wheel
          path: python/dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
