on:
  workflow_call:

jobs:

  build_python_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.13

      - name: Install the aac-rest-api Package
        run: pip install -e .[all]

      - name: Lint with flake8
        run: flake8 .

      - name: List Transitive Dependencies
        run: python -m pipdeptree

      - name: Build distribution package
        run: python -m build

      - name: Upload Python Wheel
        uses: actions/upload-artifact@v3
        with:
          name: aac_rest_api
          path: python/dist

      - name: Build Documentation
        run: |
          cp -R ../docs/ ./docs
          cd ./docs
          sphinx-build source doc_artifacts

      - name: Upload Documentation
        uses: actions/upload-artifact@v3
        with:
          name: aac-rest-api-docs
          path: python/docs/doc_artifacts
